{% set name = "IPTCInfo3" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: d602d878bb07753f20dc73addb7d149309ba7858f003bec0a1d7b6f7e626a357

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - iptcinfo3
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/IPTCInfo3/
  summary: A great way to get IPTCInfo
  license: GPL-2.0-or-later
  license_file: LICENSE

  dev_url: https://github.com/jamesacampbell/iptcinfo3

extra:
  recipe-maintainers:
    - sodre
